### PR TITLE
feat: add and refactor existing code for hazard report generator 

### PR DESCRIPTION
**Pull request by clintonlunn**

### CODE REVIEW

**Review by marshallrobinson — APPROVED** [review]
Looks great overall and generally works as expected. There are a couple minor details that are hopefully simple to take care of. Let me know if you’d like to merge and make a new ticket or fix them before merging:

- When drawing a custom area, the polygon ghosts when drawing

- The scalebar is missing beneath each map in the report

- Links on the report need to be styled as links (blue and underlined)

**Comment by marshallrobinson** [comment]
The artifacts are gone, and the scale bars are back! woohoo!

For me, the urls in the reference section don't appear as links though. Does this happen to you too?

**Review by marshallrobinson — APPROVED** [review]
The artifacts are gone, and the scale bars are back! woohoo!

For me, the urls in the reference section don't appear as links though. Does this happen to you too?

**Comment by clintonlunn** [comment]
> The artifacts are gone, and the scale bars are back! woohoo!
> 
> For me, the urls in the reference section don't appear as links though. Does this happen to you too?

@marshallrobinson 
thanks for catching that. i changed the links in the table to blue but never changed the other ones. I made it so all links i the report will be blue.

**Review by marshallrobinson — APPROVED** [review]

**Pull request merged**
